### ISSUE TITLE
Current Source Repo is not maintained. 

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/pykerberos-feedstock#20]
### Comment:

https://github.com/02strich/pykerberos

recommends using 
https://pypi.org/project/kerberos/ 
which points to 
https://github.com/apple/ccs-pykerberos

Reference - https://github.com/02strich/pykerberos/blob/master/README.txt

`NOTE: this fork of ccs-kerberos is currently on life support mode as Apple has resumed work on upstream. Please try to use https://pypi.python.org/pypi/kerberos instead of this fork if possible.`

**Comment by duncanmmacleod** [comment]
@rxm7706, given the name of the package is different on pypi, and the history is independent (same version numbers released at wildly different times), I would suggest that the 'apple' version of the Kerberos API should be a separate, new conda package, maybe called `python-kerberos` or similar, and that _this_ feedstock should be archived when the currently-attached upstream project is formally retired.

**Comment by rxm7706** [comment]
Thank you @duncanmmacleod 
Since the pypi package is called Kerberos - and from pypi history predates the pykerberos 
Do you think its ok to just call the conda-package kerberos 
Draft PR - https://github.com/conda-forge/staged-recipes/pull/24150
Please let me know if you would like to be added as a maintainer 
Or if you would like me to change the package name to be python-kerberos instead. 
Regards,

**Comment by duncanmmacleod** [comment]
Thanks, have responded, will close this out now.
